# Generated by Django 5.0.2 on 2024-03-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('ImageId', models.AutoField(primary_key=True, serialize=False)),
                ('ImagePath', models.CharField(max_length=500)),
            ],
        ),
    ]
